import jenkins.automation.utils.CheckmarxSecurityJobBuilder

def projectName ='foo'
new CheckmarxSecurityJobBuilder(
        name: "${projectName}checkmarx_security_job",
        description: "Sample checkmarx security job",
        baseUrl: "http://google.com",
        scanRepo: "https://github.com/OrlandoSoto/ckan-browser-tests",
        checkmarxComment: "Generated by Checkmarx job builder JAC",
        vulnerabilityThresholdEnabled: true,
        highThreshold: "1",
        mediumThreshold: "2",
        lowThreshold: "3"
).build(this);
