import jenkins.automation.builders.BaseJobBuilder
import jenkins.automation.utils.CheckmarxUtils

def projectName = 'foo'
def groupId = 'ac43cb0d-034d-4b1e-9bf5-e7c1c46f71d2'
def osaCheckmarxConfig =  [
    projectName: "${projectName}-checkmarx",
    groupId: "${groupId}",
    comment: 'Generated by Checkmarx job builder JAC',
    vulnerabilityThresholdEnabled: true,
    highThreshold: 1,
    mediumThreshold: 2,
    lowThreshold: 3,
    osaEnabled: true,
    osaHighThreshold: 1,
    osaMediumThreshold: 2,
    osaLowThreshold: 3,
]

new BaseJobBuilder(
        name: "${projectName}-osa-checkmarx",
        description: 'Sample checkmarx security job',
).build(this).with {
    scm {
        git {
            remote {
                url('https://github.com/champain/jenkins-automation')
            }
            branch('checkmarx_osa_fixes')
        }
    }

    steps {
        gradle {
            tasks('copyDependencies')
          }
    }

    CheckmarxUtils.checkmarxScan(delegate, osaCheckmarxConfig)
}
