import jenkins.automation.builders.CheckmarxSecurityJobBuilder

String projectName ='cfpb_osa_test'
String groupId = 'cfpb_group_id'
String presetId = 'cfpb_preset_id'
String osaFilterPattern =''
String osaPrep = '''
if [ ! -d osa_dependencies ]; then
  mkdir osa_dependencies
fi
./gradlew copy_dependencies
'''
new CheckmarxSecurityJobBuilder(
        name: "cfpb_osa_test",
        description: "CFPB OSA test, built from JAC",
        useOwnServerCredentials: false,
        serverUrl: groupId,
        groupId: groupId,
        scanRepo:[[url: "https://github.com/cfpb/jenkins_automation"]],
        checkmarxComment: "Generated by Checkmarx job builder JAC to run Checkmarx with OSA",
        preset: presetId,
        filterPattern: osaFilterPattern,
        vulnerabilityThresholdEnabled: false,
        osaCheckEnabled: true,
        osaPrepScript: osaPrep,
).build(this)
