import jenkins.automation.builders.CheckmarxSecurityJobBuilder


def projectName = "foo"
def groupId = "ac43cb0d-034d-4b1e-9bf5-e7c1c46f71d2"


new CheckmarxSecurityJobBuilder(
        name: "${projectName}-checkmarx",
        description: "Sample checkmarx security job",
        scanRepo: [
                [url: "https://github.com/OrlandoSoto/ckan-browser-tests"]
        ],
        checkmarxConfig: [
                projectName: "${projectName}-checkmarx",
                groupId: "${groupId}",
                comment: "Generated by Checkmarx job builder JAC",
                vulnerabilityThresholdEnabled: true,
                highThreshold: 1,
                mediumThreshold: 2,
                lowThreshold: 3,
        ]
).build(this);
